# generated by django 4.2.16 on 2026-04-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_session_key',
            field=models.CharField(blank=True, help_text="Session key of the user's current active session. A new login invalidates the previous one.", max_length=40, null=True),
        ),
    ]
