# Generated by Django 4.2.16 on 2026-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_active_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attendance_session_minutes',
            field=models.PositiveIntegerField(
                default=60,
                help_text='For teacher accounts, attendance sessions stay open for this many minutes.',
            ),
        ),
    ]
