# generated by django 4.2.16 on 2026-04-06 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=50)),
                ('university_roll_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('enrollment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.academicclass', verbose_name='Class / Program')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.academicyear', verbose_name='Academic Year')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to=settings.AUTH_USER_MODEL)),
                ('enrolled_subjects', models.ManyToManyField(blank=True, related_name='enrolled_students', to='attendance.subject', verbose_name='Enrolled Subjects')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='student_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_payload', models.TextField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('last_regenerated_at', models.DateTimeField(auto_now=True)),
                ('signing_key_version', models.IntegerField(default=1)),
                ('is_valid', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_record', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', models.TextField()),
                ('model_name', models.CharField(default='SFace_v1.0', max_length=100)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('source_image_hash', models.CharField(blank=True, max_length=64)),
                ('capture_environment', models.CharField(choices=[('WELL_LIT', 'Well Lit'), ('DIM', 'Dim'), ('OUTDOOR', 'Outdoor'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
