# Generated by Django 4.2.16 on 2026-03-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user_studentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university_roll_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
