# Generated by Django 4.2.16 on 2026-04-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_university_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentphoto',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
