# Generated by Django 4.2.16 on 2026-04-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentphoto_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentphoto',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='studentphoto',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
