# Generated by Django 4.2.16 on 2026-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_edited_at_and_more'),
        ('students', '0005_remove_studentphoto_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='attendance.subject'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
