# Generated by Django 4.2.16 on 2026-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_edited_at_and_more'),
        ('students', '0006_alter_student_unique_together_student_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='attendance.section', verbose_name='Subjects (Sections)'),
        ),
    ]
