# Generated by Django 4.2.16 on 2026-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='auto_close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
