# Generated by Django 4.2.16 on 2026-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_batch_subject_section_batch_section_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='mode',
            field=models.CharField(choices=[('IN_PERSON', 'In-Person'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='IN_PERSON', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'student'], name='attendance__session_b22fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
    ]
