# Generated by Django 4.2.16 on 2026-04-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancerecord_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
    ]
