# Generated by Django 4.2.16 on 2026-04-07 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='target_resource',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_role',
            field=models.CharField(blank=True, help_text='Role at the time of the event', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID string of actor (denormalised)', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_username',
            field=models.CharField(blank=True, help_text='Username at the time of the event', max_length=150),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='auth_method',
            field=models.CharField(choices=[('password', 'Password'), ('facial_recognition', 'Facial Recognition'), ('otp', 'OTP'), ('mfa', 'MFA'), ('system', 'System / Internal'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='browser',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='checksum',
            field=models.CharField(blank=True, help_text='HMAC-SHA256 of immutable fields', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value context: logout reason, error codes, stack traces, …'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('BIO_LOGIN', 'Biometric Login'), ('BIO_LOGIN_FAILED', 'Biometric Login Failed'), ('BIO_AUTH_LOCKED', 'Biometric Auth Locked'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET_REQ', 'Password Reset Requested'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('OTP_FAILED', 'OTP Verification Failed'), ('USER_CREATED', 'User Created'), ('USER_AUTO_CREATED', 'User Auto-Created'), ('USER_MODIFIED', 'User Modified'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('SESSION_EXPIRED', 'Session Expired'), ('ACCESS_DENIED', 'Access Denied'), ('CSRF_FAILURE', 'CSRF Failure'), ('ERROR', 'Error'), ('ADMIN_ACTION', 'Admin Action'), ('PURGE', 'Log Purge'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='os',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='al_evtype_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_user_id', 'timestamp'], name='al_userid_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='al_ip_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['auth_method', 'timestamp'], name='al_authm_ts_idx'),
        ),
    ]
